name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 17번 자바를 완벽하게 세팅해주는 마법의 단계가 추가되었습니다.
    - name: Set up JDK 17
      id: setup-jdk
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # 불필요했던 자바 설치 코드가 빠져서 더 깔끔하고 가벼워졌습니다.
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev
        pip install --upgrade pip
        pip install buildozer cython setuptools

    - name: Build with Buildozer
      run: yes | buildozer -v android debug
